import { describe, it, expect } from 'vitest';
import { test } from '@fast-check/vitest';
import * as fc from 'fast-check';

// Feature: developer-portfolio, Property 17: SEO Meta Tags
// Validates: Requirements 10.1

describe('Property 17: SEO Meta Tags', () => {
  test.prop([
    fc.record({
      title: fc.string({ minLength: 1, maxLength: 100 }),
      description: fc.string({ minLength: 1, maxLength: 200 }),
      image: fc.option(fc.webUrl(), { nil: undefined }),
    })
  ], { numRuns: 100 })('all pages include required meta tags', (pageProps) => {
    // Simulate the meta tags that would be generated by BaseLayout
    const metaTags = generateMetaTags(pageProps);
    
    // Required meta tags
    expect(metaTags).toHaveProperty('title');
    expect(metaTags.title).toBe(pageProps.title);
    
    expect(metaTags).toHaveProperty('description');
    expect(metaTags.description).toBe(pageProps.description);
    
    // Open Graph properties
    expect(metaTags).toHaveProperty('og:type');
    expect(metaTags['og:type']).toBe('website');
    
    expect(metaTags).toHaveProperty('og:title');
    expect(metaTags['og:title']).toBe(pageProps.title);
    
    expect(metaTags).toHaveProperty('og:description');
    expect(metaTags['og:description']).toBe(pageProps.description);
    
    expect(metaTags).toHaveProperty('og:url');
    expect(metaTags['og:url']).toBeTruthy();
    
    expect(metaTags).toHaveProperty('og:image');
    expect(metaTags['og:image']).toBeTruthy();
    
    // Twitter Card properties
    expect(metaTags).toHaveProperty('twitter:card');
    expect(metaTags['twitter:card']).toBe('summary_large_image');
    
    expect(metaTags).toHaveProperty('twitter:title');
    expect(metaTags['twitter:title']).toBe(pageProps.title);
    
    expect(metaTags).toHaveProperty('twitter:description');
    expect(metaTags['twitter:description']).toBe(pageProps.description);
    
    expect(metaTags).toHaveProperty('twitter:image');
    expect(metaTags['twitter:image']).toBeTruthy();
  });
});

// Helper function that simulates BaseLayout's meta tag generation logic
function generateMetaTags(props: { title: string; description: string; image?: string }) {
  const site = 'https://example.github.io';
  const canonicalURL = `${site}/`;
  const socialImage = props.image || `${site}og-default.png`;
  
  return {
    title: props.title,
    description: props.description,
    'og:type': 'website',
    'og:url': canonicalURL,
    'og:title': props.title,
    'og:description': props.description,
    'og:image': socialImage,
    'twitter:card': 'summary_large_image',
    'twitter:url': canonicalURL,
    'twitter:title': props.title,
    'twitter:description': props.description,
    'twitter:image': socialImage,
  };
}
